[build]
  base = "."
  publish = "_site"
  command = "npm run build"

# These things are also done as part of the Eleventy build process, but this shouldn't be a problem.
[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.images]
  compress = true
[build.processing.html]
  pretty_urls = true
